service: serverless-bolt-python
frameworkVersion: '2'
package:
  individually: true
  exclude:
    - "*/**"
provider:
  name: aws
  runtime: python3.8
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn" ] }
    - Effect: Allow
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::oauthinstallationv2/*"
        - "arn:aws:s3:::oauthstatev2/*"
        - "arn:aws:s3:::oauthinstallationv2"
        - "arn:aws:s3:::oauthstatev2"
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        - "arn:aws:sns:*"
        - "arn:aws:sts::*"
        - { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.purgeTopicName}" ] ]  }

  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
    SLACK_SCOPES : "app_mentions:read, commands,chat:write"
    SLACK_INSTALLATION_S3_BUCKET_NAME :  "oauthinstallationv2"
    SLACK_STATE_S3_BUCKET_NAME : "oauthstatev2"
    CF_API_KEY: ${env:CF_API_KEY}
    USERS_TABLE: ${self:custom.tableName}
    PURGE_TOPIC: ${self:custom.snsPurgeTopicArn.${self:provider.stage}}
functions:
  slack:
    handler: app.handler
    timeout: 12
    events:
      - httpApi:
          path: /auth
          method: ANY
      - http:
          path: /slack/events
          method: POST
      - s3: oauthinstallationv2
      - s3: oauthstatev2
      - sns: ${self:custom.purgeTopicName}
    package:
      include:
        - app.py
plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dynamodb-local
resources:
  Resources:
    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
custom:
  tableName: 'users-table-${self:provider.stage}'
  purgeTopicName: "${self:service}-${self:provider.stage}-purge-topic"
  snsPurgeTopicArn:
    local:
      "arn:aws:sns:us-east-1:123456789012:${self:custom.purgeTopicName}"
    dev:
      { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.purgeTopicName}" ] ]  }
    prod:
      { "Fn::Join" : ["", ["arn:aws:sns:${self:provider.region}:", { "Ref" : "AWS::AccountId" }, ":${self:custom.purgeTopicName}" ] ]  }
  pythonRequirements:
    dockerizePip: true
useDotenv: true